(function(){
const varieties=[
 {name:'NSIC Rc222',local:'Tubigan 18',maturity:'110–115 days',type:'Semi-dwarf',season:'Wet / Dry',traits:'Good yield potential; widely used in irrigated rice areas.',note:'Common choice for farmers looking for a dependable irrigated variety.'},
 {name:'NSIC Rc300',local:'Tubigan 3',maturity:'105–110 days',type:'Semi-dwarf',season:'Wet / Dry',traits:'Early to medium maturity with good grain quality.',note:'Useful where harvest timing and grain quality are priorities.'},
 {name:'NSIC Rc216',local:'Tubigan 17',maturity:'110–115 days',type:'Semi-dwarf',season:'Wet / Dry',traits:'Good adaptation to irrigated lowland conditions.',note:'Consider local soil, water and disease pressure before selection.'}
];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const s=document.querySelector('#crops');if(!s||s.dataset.catalog==='1')return;s.dataset.catalog='1';s.innerHTML=`<div class="section-head"><div><small>Agrisense Knowledge Base</small><h2>🌱 Crop Varieties</h2></div></div><div class="card compact crop-intro"><h3>Varieties at Characteristics</h3><p>Piliin ang variety para makita ang basic characteristics nito. Gagamitin din ng Agrisense ang napiling variety bilang isa sa inputs sa farm assessment.</p></div>${varieties.map((v,i)=>`<button class="crop-variety" onclick="window.openCropVariety(${i})"><div class="crop-variety-main"><div><b>🌾 ${esc(v.name)}</b><small>${esc(v.local)}</small></div><span>›</span></div><div class="crop-tags"><span>${esc(v.maturity)}</span><span>${esc(v.season)}</span></div><p>${esc(v.traits)}</p></button>`).join('')}<div class="card compact"><h3>📌 Important</h3><p>Ang characteristics ay reference lamang. Ang final recommendation ay dapat naka-base pa rin sa actual farm condition, weather, soil information at local agricultural guidance.</p></div>`}
window.openCropVariety=function(i){const v=varieties[i];const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="sheet"><div class="row"><div><small>Crop variety</small><h2>🌾 ${esc(v.name)}</h2></div><button onclick="this.closest('.modal').remove()">✕</button></div><div class="card compact"><div class="grid"><div class="stat"><b>${esc(v.maturity)}</b><small>Maturity</small></div><div class="stat"><b>${esc(v.type)}</b><small>Plant type</small></div><div class="stat"><b>${esc(v.season)}</b><small>Suitable season</small></div><div class="stat"><b>${esc(v.local)}</b><small>Local name</small></div></div><h3>Characteristics</h3><p>${esc(v.traits)}</p><p>${esc(v.note)}</p></div><button class="primary wide" onclick="this.closest('.modal').remove()">Okay</button></div>`;document.body.appendChild(m)};
new MutationObserver(render).observe(document.body,{childList:true,subtree:true});setTimeout(render,50);
})();
