(function(){
 const KEY='agrisense';
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=()=>JSON.parse(localStorage.getItem(KEY)||'{}');
 function ndviInfo(n){if(n==null)return ['—','Waiting for Sentinel-2 bands'];let x=Number(n);if(!Number.isFinite(x))return ['—','No valid NDVI'];if(x<0.2)return [x.toFixed(2),'Very low vegetation signal'];if(x<0.4)return [x.toFixed(2),'Low vegetation signal'];if(x<0.6)return [x.toFixed(2),'Moderate vegetation signal'];if(x<0.8)return [x.toFixed(2),'Healthy vegetation signal'];return [x.toFixed(2),'Very strong vegetation signal']}
 function renderIntel(){
  const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;
  let btn=nav.querySelector('[data-s="intel"]');if(!btn){btn=document.createElement('button');btn.dataset.s='intel';btn.innerHTML='<span>🛰️</span>Intel';btn.onclick=()=>goIntel();nav.appendChild(btn)}
  let sec=document.querySelector('#intel');if(!sec){sec=document.createElement('section');sec.id='intel';sec.className='screen';main.appendChild(sec)}
  const data=read(),e=data.earth||{},s=e.sentinel,w=e.weather,nd=ndviInfo(s?.ndvi??e.ndvi);const items=s?.items||[];
  sec.innerHTML='<div class="section-head"><div><small>Evidence & Analysis</small><h2>🧠 Agrisense Intelligence</h2></div></div>'+
   '<div class="card compact"><div class="row"><div><h3>🛰️ Sentinel-2</h3><small>Satellite observation</small></div><span class="status '+(s?'':'warn')+'">'+(s?(s.count||items.length||0)+' match':'Not checked')+'</span></div>'+
   '<div class="grid intel-grid"><div class="stat"><b>'+esc(nd[0])+'</b><small>NDVI</small></div><div class="stat"><b>'+esc(nd[1])+'</b><small>Vegetation signal</small></div></div>'+
   '<div class="metric-list"><div>NDMI <b>—</b><small>Water-stress signal · requires NIR/SWIR</small></div><div>NDRE <b>—</b><small>Chlorophyll signal · requires red-edge bands</small></div><div>EVI <b>—</b><small>Vegetation index · requires blue/NIR/red</small></div><div>Vegetation trend <b>Waiting</b><small>Needs multiple clear observations</small></div></div>'+
   (items.length?items.slice(0,5).map(i=>'<button class="observation" type="button"><div><b>Sentinel-2 Level-2A</b><small>'+esc(i.date||'Latest observation')+'</small></div><span>'+((i.cloud_cover==null)?'—':Math.round(i.cloud_cover)+'% cloud')+'</span></button>').join(''):'<p class="muted">Mag-refresh ng Live Earth Data para maghanap ng satellite observation.</p>')+'</div>'+
   '<div class="card compact"><div class="row"><div><h3>🌦️ NASA POWER</h3><small>Weather evidence</small></div><span class="status '+(w?'':'warn')+'">'+(w?'Available':'Not checked')+'</span></div>'+
   (w?'<div class="grid"><div class="stat"><b>'+((w.temperature_c==null)?'—':Number(w.temperature_c).toFixed(1)+'°C')+'</b><small>Temperature</small></div><div class="stat"><b>'+((w.precipitation_mm==null)?'—':Number(w.precipitation_mm).toFixed(1)+' mm')+'</b><small>Rainfall</small></div><div class="stat"><b>'+((w.humidity_pct==null)?'—':Number(w.humidity_pct).toFixed(0)+'%')+'</b><small>Humidity</small></div><div class="stat"><b>'+((w.solar_radiation_mj_m2==null)?'—':Number(w.solar_radiation_mj_m2).toFixed(1))+'</b><small>Solar radiation</small></div><div class="stat"><b>'+((w.wind_speed_m_s==null)?'—':Number(w.wind_speed_m_s).toFixed(1)+' m/s')+'</b><small>Wind</small></div><div class="stat"><b>'+((w.pressure_kpa==null)?'—':Number(w.pressure_kpa).toFixed(1)+' kPa')+'</b><small>Pressure</small></div></div><p class="muted">Latest available weather evidence for the selected farm. Forecast and accumulated-rain indicators will be added when the API provides them.</p>':'<p class="muted">Mag-refresh ng Live Earth Data para makakuha ng NASA POWER weather data.</p>')+'</div>'+
   '<div class="card compact"><h3>🧠 Prediction evidence</h3><div class="evidence-list"><span>• Sentinel-2 vegetation & imagery</span><span>• NDVI / NDMI / NDRE / EVI when source bands are available</span><span>• Multi-date vegetation trend</span><span>• NASA POWER temperature, rainfall, humidity</span><span>• Solar radiation, wind & pressure</span><span>• Crop variety, characteristics & growth stage</span><span>• Farmer field reports</span></div><p class="muted">Agrisense combines independent evidence sources before producing a farm-specific risk score. Missing or cloudy data lowers confidence instead of inventing a value.</p></div>';
 }
 window.goIntel=function(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelector('#intel')?.classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.s==='intel'));scrollTo(0,0);renderIntel()};
 new MutationObserver(()=>setTimeout(renderIntel,0)).observe(document.body,{childList:true,subtree:true});setTimeout(renderIntel,150);
})();