(function(){
 function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
 function patch(){
  const screen=document.querySelector('#intel');if(!screen)return;
  if(!screen.dataset.summary){
   const first=screen.querySelector('.card');
   if(first){const box=document.createElement('div');box.className='card farmer-summary';box.innerHTML='<div class="muted">Agrisense quick check</div><div class="title" style="margin-top:3px">🌾 Ano ang ibig sabihin nito?</div><p class="muted" style="margin:8px 0 0">Pinagsasama namin ang satellite, weather, crop stage at field reports para makabuo ng assessment.</p><div class="row" style="margin-top:12px"><span class="status warn">Confidence: Kumokolekta pa ng ebidensya</span></div><p class="muted" style="margin:8px 0 0">Hindi muna maglalabas ng percentage hangga’t kulang ang supporting data.</p>';first.before(box);screen.dataset.summary='1'}
  }
  const cards=screen.querySelectorAll('.card');
  const sentinel=[...cards].find(c=>c.textContent.includes('Sentinel-2'));if(!sentinel)return;
  const map=sentinel.querySelector('.map');if(map)map.remove();
  [...sentinel.querySelectorAll('.row')].filter(r=>r.querySelector('.status')&&r!==sentinel.querySelector('.row')&&!r.classList.contains('earth-match')).forEach(row=>{
   const status=row.querySelector('.status')?.textContent.trim()||'';const dateText=(row.querySelector('b')?.textContent||'').trim();const id=(row.querySelector('.muted')?.textContent||'').trim()||row.textContent.trim();const item={id,date:dateText,cloud_cover:parseFloat(status)};
   const b=document.createElement('button');b.type='button';b.className='earth-match';b.innerHTML='<div class="earth-match-head"><div class="earth-match-title"><strong>🛰️ Sentinel-2 Level-2A</strong><div class="earth-id">'+esc(id)+'</div></div><span class="status">'+(Number.isFinite(item.cloud_cover)?Math.round(item.cloud_cover)+'% cloud':'—')+'</span></div><div class="muted earth-match-date">'+esc(dateText)+' · Tap para makita ang observation</div>';b.onclick=()=>detail(item);row.replaceWith(b);
  });
  [...screen.querySelectorAll('.card')].filter(c=>c.textContent.includes('NASA POWER')).forEach(c=>{const p=c.querySelector('p.muted');if(p&&p.textContent.includes('Observation:'))p.innerHTML=p.innerHTML.replace('Observation:','Pinakabagong available:')});
 }
 function detail(i){const m=document.createElement('div');m.className='modal open';const cloud=Number.isFinite(i.cloud_cover)?Math.round(i.cloud_cover):null;const note=cloud!==null&&cloud>=40?'May ulap sa image. Gamitin muna ito bilang reference at huwag gumawa ng strong crop conclusion mula sa satellite image lang.':'Mas malinaw ang satellite image at maaari itong gamitin bilang isang ebidensya sa field assessment.';m.innerHTML='<div class="sheet"><div class="row"><div><div class="muted">Satellite observation</div><div class="title">🛰️ Sentinel-2 Level-2A</div></div><button onclick="this.closest(\'.modal\').remove()">✕</button></div><div class="card" style="margin-top:14px;background:#f8fcf9"><div class="grid"><div class="stat"><b>'+esc(i.date||'—')+'</b><small>Petsa ng image</small></div><div class="stat"><b>'+(cloud===null?'—':cloud+'%')+'</b><small>Cloud sa image</small></div></div><p class="muted" style="margin-top:12px;word-break:break-word"><b>Technical ID:</b> '+esc(i.id)+'</p></div><div class="card"><div class="title">Para sa farmer</div><p class="muted">'+note+'</p><p class="muted">Hindi ito diagnosis. Isasama ito sa weather, crop stage at field reports bago gumawa ng risk assessment.</p></div><button class="primary" onclick="this.closest(\'.modal\').remove()">Okay</button></div>';document.body.appendChild(m)}
 new MutationObserver(()=>setTimeout(patch,0)).observe(document.body,{childList:true,subtree:true});setTimeout(patch,100);
})();